version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started...
      - npm run build
artifacts:
  base-directory: build
  files:
    - '**/*'
